Repository CodeForAfrica/actNOW, pull requests merged in 2021-07, with the labels that each got.

#59 Ft user registration profile
  actnow/accounts/models.py
  actnow/accounts/serializers.py
  actnow/accounts/tests/test_models.py
  actnow/accounts/tests/test_views.py
  actnow/petitions/tests/test_models.py
  actnow/profiles/migrations/0006_auto_20210701_1251.py
  actnow/profiles/models.py
  actnow/profiles/serializers.py
  actnow/profiles/signals.py
  actnow/profiles/tests/model_factory.py
  actnow/profiles/tests/test_models.py
  actnow/profiles/tests/test_views.py
  actnow/profiles/views.py
Labels: enhancement

#72 [HotFix] Blank charfields
  actnow/accounts/models.py
  actnow/accounts/serializers.py
  actnow/profiles/migrations/0007_alter_model_blank_charfields.py
  actnow/profiles/models.py
Labels: bug

#68 Adds an issue to a petition.
  actnow/petitions/admin.py
  actnow/petitions/migrations/0002_add_source_to_pettition.py
  actnow/petitions/models.py
  actnow/petitions/serializers.py
  requirements-all.txt
Labels: enhancement

#76 Ft allow users to follow a petition#178843742
  actnow/petitions/migrations/0003_petition_followers.py
  actnow/petitions/models.py
  actnow/petitions/serializers.py
  actnow/petitions/urls.py
  actnow/petitions/views.py
  actnow/settings.py
Labels: enhancement

#92 [Fix] User accounts defaults
  actnow/accounts/models.py
  actnow/accounts/tests/test_models.py
  requirements-all.txt
  setup.cfg
Labels: bug, chore, dependencies

#96 [Feat] Petitions creation api
  actnow/petitions/serializers.py
  actnow/petitions/tests/test_views.py
  actnow/petitions/urls.py
  actnow/petitions/views.py
  actnow/settings.py
Labels: enhancement
