Repository CodeForAfrica/actNOW, pull requests merged in 2021-06, with the labels that each got.

#14 Feature user registration api 178347129
  actnow/accounts/serializers.py
  actnow/accounts/tests/test_serializers.py
  actnow/accounts/tests/test_views.py
  actnow/accounts/urls.py
  actnow/accounts/utils.py
  actnow/accounts/views.py
  actnow/settings.py
  actnow/urls.py
Labels: enhancement

#15 Ft oauth2 provider
  actnow/accounts/admin.py
  actnow/settings.py
  actnow/urls.py
  contrib/docker-compose/nginx/default.conf
  nginx.conf.sigil
  requirements-all.txt
  templates/admin/login.html
Labels: enhancement

#16 Sets up continuous delivery
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: chore

#17 Ft user profile
  actnow/profiles/__init__.py
  actnow/profiles/admin.py
  actnow/profiles/apps.py
  actnow/profiles/migrations/0001_initial.py
  actnow/profiles/migrations/__init__.py
  actnow/profiles/models.py
  actnow/profiles/tests/__init__.py
  actnow/profiles/tests/model_factory.py
  actnow/profiles/tests/test_models.py
  actnow/profiles/validators.py
  actnow/profiles/views.py
  actnow/settings.py
  contrib/docker-compose/nginx/default.conf
  docker-compose.yml
  requirements-all.txt
  requirements-dev.txt
Labels: enhancement

#21 Adds an Organisation
  actnow/profiles/admin.py
  actnow/profiles/apps.py
  actnow/profiles/migrations/0002_organisationprofile.py
  actnow/profiles/models.py
  actnow/profiles/signals.py
  actnow/profiles/tests/model_factory.py
  actnow/profiles/tests/test_models.py
Labels: enhancement

#27 [Fix] Accounts and profiles models
  actnow/accounts/migrations/0002_actnow_user_match_abstract_user.py
  actnow/accounts/migrations/0003_alter_actnowuser_email.py
  actnow/accounts/migrations/0004_timestamp_models.py
  actnow/accounts/models.py
  actnow/db/__init__.py
  actnow/db/apps.py
  actnow/db/migrations/__init__.py
  actnow/db/models.py
  actnow/profiles/migrations/0003_profile_fields.py
  actnow/profiles/migrations/0004_timestamp_models.py
  actnow/profiles/models.py
  actnow/settings.py
Labels: bug, chore, enhancement

#31 Link Organisation Profile to user accounts instead of user profiles
  actnow/profiles/migrations/0005_alter_organisationprofile_persons.py
  actnow/profiles/models.py
  actnow/profiles/tests/test_models.py
Labels: enhancement

#30 [Chore] Docker setup
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  Dockerfile
  contrib/docker-compose/wait-for-postgres.sh
  docker-compose.yml
Labels: chore

#33 Ensure only apps(With registered users) can register new users
  actnow/accounts/apps.py
  actnow/accounts/migrations/0005_actnowapplication.py
  actnow/accounts/models.py
  actnow/accounts/permissions.py
  actnow/accounts/signals.py
  actnow/accounts/tests/test_views.py
  actnow/accounts/urls.py
  actnow/accounts/views.py
  actnow/settings.py
Labels: enhancement

#28 Add Petition
  actnow/petitions/__init__.py
  actnow/petitions/admin.py
  actnow/petitions/apps.py
  actnow/petitions/migrations/0001_initial.py
  actnow/petitions/migrations/__init__.py
  actnow/petitions/models.py
  actnow/petitions/serializers.py
  actnow/petitions/tests/__init__.py
  actnow/petitions/tests/test_models.py
  actnow/petitions/urls.py
  actnow/petitions/views.py
  actnow/settings.py
  actnow/urls.py
Labels: enhancement

#37 Ft user account management
  actnow/accounts/admin.py
  actnow/accounts/migrations/0006_add_is_deleted_attribute.py
  actnow/accounts/models.py
  actnow/accounts/permissions.py
  actnow/accounts/serializers.py
  actnow/accounts/tests/test_models.py
  actnow/accounts/tests/test_serializers.py
  actnow/accounts/tests/test_views.py
  actnow/accounts/urls.py
  actnow/accounts/utils.py
  actnow/accounts/views.py
  actnow/petitions/serializers.py
  actnow/settings.py
  templates/_base.html
  templates/oauth2_provider/authorize.html
  templates/registration/login.html
Labels: enhancement

#44 Adds an organisation profile API endpoint.
  actnow/profiles/permissions.py
  actnow/profiles/serializers.py
  actnow/profiles/urls.py
  actnow/profiles/views.py
  actnow/urls.py
Labels: enhancement

#42 Ft user profile management
  actnow/profiles/permissions.py
  actnow/profiles/serializers.py
  actnow/profiles/tests/test_views.py
  actnow/profiles/urls.py
  actnow/profiles/views.py
Labels: enhancement

#54 [Chore] AWS S3 Storages
  actnow/settings.py
  actnow/storages_backends.py
  requirements-all.txt
Labels: chore

#55 [Chore] Site
  .env.template
  actnow/settings.py
  actnow/site/__init__.py
  actnow/site/apps.py
  actnow/site/migrations/__init__.py
  actnow/site/static/img/logo.png
  actnow/site/templates/index.html
  actnow/site/urls.py
  actnow/site/views.py
  actnow/urls.py
  docker-compose.yml
  templates/_base.html
Labels: chore, enhancement
