Repository CodeForAfrica/actNOW, pull requests merged in 2021-05, with the labels that each got.

#7 Fixes GitHub actions OOM error.
  actnow/settings.py
  docker-compose.yml
Labels: bug

#8 Fix docker compose startup
  Dockerfile
  contrib/docker/entrypoint.sh
  docker-compose.yml
Labels: bug

#4 [Chore] Docker GitHub Action
  .github/dependabot.yml
  .github/workflows/pull_request.yml
  Makefile
  docker-compose.yml
  requirements-all.txt
  requirements-dev.txt
Labels: chore

#6 Use email as username 178177525
  actnow/accounts/__init__.py
  actnow/accounts/admin.py
  actnow/accounts/apps.py
  actnow/accounts/backends.py
  actnow/accounts/forms.py
  actnow/accounts/migrations/0001_initial.py
  actnow/accounts/migrations/__init__.py
  actnow/accounts/models.py
  actnow/accounts/templates/login.html
  actnow/accounts/tests/__init__.py
  actnow/accounts/tests/test_models.py
  actnow/accounts/views.py
  actnow/settings.py
  actnow/urls.py
Labels: enhancement
